"use client";
import { useParams } from "next/navigation";import Link from "next/link";import { motion } from "framer-motion";import { subjects, getTerms } from "@/lib/data";import { ChevronRight, BookOpen, Clock, BarChart3, PlayCircle, CheckCircle, Circle, GraduationCap } from "lucide-react";
export default function SubjectDetailPage(){const p=useParams();const sub=subjects.find(s=>s.id===p.subjectId);
if(!sub)return(<div className="max-w-7xl mx-auto px-4 py-16 text-center"><div className="text-4xl mb-4">📚</div><h2 className="text-xl font-bold mb-2">Subject Not Found</h2><Link href="/subjects"className="btn btn-p">Back to Subjects</Link></div>);
const terms=getTerms(sub.id);
return(<div className="max-w-7xl mx-auto px-4 py-8"><div className="flex items-center gap-2 text-sm text-[var(--fg3)] mb-6"><Link href="/subjects"className="hover:text-[var(--fg)]">Subjects</Link><ChevronRight className="w-4 h-4"/><span className="text-[var(--fg)] font-medium">{sub.name}</span></div>
<motion.div initial={{opacity:0,y:20}}animate={{opacity:1,y:0}}className="card card-p md:p-8 mb-8"><div className="flex items-start gap-6"><div className="w-16 h-16 rounded-2xl flex items-center justify-center text-3xl shadow-lg"style={{background:`linear-gradient(135deg,${sub.color},${sub.color}cc)`}}>{sub.icon}</div><div className="flex-1"><h1 className="text-2xl font-bold mb-2">{sub.name}</h1><p className="text-[var(--fg2)] mb-4">{sub.desc}</p><div className="flex flex-wrap gap-4 text-sm"><span className="flex items-center gap-1.5"><BookOpen className="w-4 h-4"/>{sub.lessons} Lessons</span><span className="flex items-center gap-1.5"><BarChart3 className="w-4 h-4"/>{sub.questions}+ Questions</span><span className="flex items-center gap-1.5"><Clock className="w-4 h-4"/>3 Terms</span></div></div></div></motion.div>
<div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">{[{icon:PlayCircle,label:"Start Learning",href:`/subjects/${sub.id}/term-1/week-1`},{icon:GraduationCap,label:"Practice CBT",href:`/cbt?subject=${sub.id}`},{icon:BookOpen,label:"Flashcards",href:`/study/flashcards?subject=${sub.id}`},{icon:BarChart3,label:"View Progress",href:"/dashboard/analytics"}].map(a=>(<Link key={a.label}href={a.href}className="card card-click card-p flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-brand-100 dark:bg-brand-900/20 flex items-center justify-center"><a.icon className="w-5 h-5 text-brand-600"/></div><span className="text-sm font-semibold">{a.label}</span></Link>))}</div>
<h2 className="text-xl font-bold mb-4">Course Structure</h2>
<div className="space-y-6">{terms.map((term,ti)=>(<motion.div key={term.id}initial={{opacity:0,y:20}}animate={{opacity:1,y:0}}transition={{delay:ti*0.1}}className="card overflow-hidden"><div className="p-5 border-b border-[var(--border)] bg-[var(--bg2)]"><div className="flex items-center justify-between"><div><h3 className="font-bold text-lg">{term.name}</h3><p className="text-sm text-[var(--fg3)]">{term.weeks.length} weeks</p></div></div></div><div className="divide-y divide-[var(--border)]">{term.weeks.map(w=>(<Link key={w.id}href={`/subjects/${sub.id}/${term.id}/${w.id}`}className="flex items-center gap-4 p-4 hover:bg-[var(--bg2)] transition-colors group"><div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 ${w.status==="Completed"?"bg-emerald-100 dark:bg-emerald-900/20 text-emerald-600":w.status==="In Progress"?"bg-brand-100 dark:bg-brand-900/20 text-brand-600":"bg-[var(--bg3)] text-[var(--fg3)]"}`}>{w.status==="Completed"?<CheckCircle className="w-4 h-4"/>:w.status==="In Progress"?<PlayCircle className="w-4 h-4"/>:<Circle className="w-4 h-4"/>}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2 mb-0.5"><span className="text-xs font-medium text-[var(--fg3)]">Week {w.number}</span><span className={`text-xs px-2 py-0.5 rounded-full ${w.difficulty==="Easy"?"bg-emerald-100 text-emerald-700":w.difficulty==="Medium"?"bg-amber-100 text-amber-700":"bg-red-100 text-red-700"}`}>{w.difficulty}</span></div><h4 className="font-semibold group-hover:text-brand-700">{w.topic}</h4><p className="text-xs text-[var(--fg3)] mt-0.5">{w.subtopics.join(" • ")}</p></div><div className="hidden md:flex items-center gap-2"><span className="text-xs text-[var(--fg3)]">{w.duration}</span></div><ChevronRight className="w-4 h-4 text-[var(--fg3)] group-hover:text-brand-700"/></Link>))}</div></motion.div>))}</div></div>);}